apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dfd
  namespace: calunga--runtime-int
  labels:
    app.kubernetes.io/part-of: dfd
spec:
  project: default

  source:
    repoURL: https://github.com/calungaproject/dfd.git
    targetRevision: main
    path: manifests/overlays/mp-plus

  destination:
    server: https://kubernetes.default.svc
    namespace: calunga--runtime-int

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status
        - /spec/host
