apiVersion: v1
kind: Service
metadata:
  name: dfd-postgresql
  namespace: dfd
  labels:
    app: dfd
    component: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: dfd
    component: postgresql
